apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: etcd-data-sc
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
    - node3
